stages:
  - build

before_script:
  - git submodule update --init --recursive

.build_template:
  stage: build
  tags:
    - build
  artifacts:
    paths:
      - "${IDF_PATH}/${IDF_EXAMPLE_PATH}/build*/build_log.txt"
    when: always
    expire_in: 4 days
  script:
    - source ${IDF_PATH}/export.sh
    - pip install idf-component-manager idf-build-apps --upgrade
    # Need to rename the cloned "esp_hosted_mcu" directory since the injected component name is "esp_hosted"
    - cd .. && rm -rf esp_hosted && mv esp_hosted_mcu esp_hosted && cd esp_hosted
    # Replaces esp_hosted component in example's deps with the one from the current repository
    - export OVERRIDE_PATH=`pwd`
    - cd ${IDF_PATH}/${IDF_EXAMPLE_PATH}
    - cat ${OVERRIDE_PATH}/.gitlab-ci-override-idf-component.yml >> main/idf_component.yml
    # Build with IDF pedantic flags and IDF build apps script
    - export PEDANTIC_FLAGS="-DIDF_CI_BUILD -Werror -Werror=deprecated-declarations -Werror=unused-variable -Werror=unused-but-set-variable -Werror=unused-function"
    - export EXTRA_CFLAGS="${PEDANTIC_FLAGS} -Wstrict-prototypes"
    - export EXTRA_CXXFLAGS="${PEDANTIC_FLAGS}"
    - idf-build-apps find --config sdkconfig.ci* -vv --target ${IDF_TARGET}
    - idf-build-apps build --config sdkconfig.ci* -vv --target ${IDF_TARGET}
    # Rename back, since post scripts expect the original name
    - cd ${OVERRIDE_PATH} && cd .. && mv esp_hosted esp_hosted_mcu


build_idf_v5.3:
  extends: .build_template
  image: ${CI_DOCKER_REGISTRY}/esp-env-v5.3
  parallel:
    matrix:
      - IDF_TARGET: ["esp32p4", "esp32h2", "esp32s3"]
        IDF_EXAMPLE_PATH: examples/protocols/mqtt/tcp

build_idf_v5.4:
  extends: .build_template
  image: ${CI_DOCKER_REGISTRY}/esp-env-v5.4
  parallel:
    matrix:
      - IDF_TARGET: ["esp32p4", "esp32h2", "esp32s3"]
        IDF_EXAMPLE_PATH: examples/protocols/mqtt/tcp

build_idf_v5.5:
  extends: .build_template
  image: ${CI_DOCKER_REGISTRY}/esp-env-latest
  parallel:
    matrix:
      - IDF_TARGET: ["esp32p4", "esp32h2", "esp32s3"]
        IDF_EXAMPLE_PATH: [examples/protocols/mqtt/tcp, examples/wifi/iperf]
